package com.nook.app

import android.annotation.SuppressLint
import android.content.Context
import com.google.firebase.FirebaseApp

/** Build-time keys (from local.properties → BuildConfig). Never hard-code real values here. */
object AppConfig {
    val workerUrl: String get() = BuildConfig.WORKER_URL.trimEnd('/')
    val cloudinaryCloud: String get() = BuildConfig.CLOUDINARY_CLOUD_NAME
    val cloudinaryPreset: String get() = BuildConfig.CLOUDINARY_UPLOAD_PRESET
    val giphyKey: String get() = BuildConfig.GIPHY_API_KEY
    val liveKitUrl: String get() = BuildConfig.LIVEKIT_URL

    val hasWorker get() = workerUrl.isNotBlank()
    val hasCloudinary get() = cloudinaryCloud.isNotBlank() && cloudinaryPreset.isNotBlank()
    val hasGiphy get() = giphyKey.isNotBlank()
    val hasLiveKit get() = liveKitUrl.isNotBlank()

    const val MAX_FILE_BYTES = 10L * 1024 * 1024
    const val PAGE_SIZE = 30L

    fun firebaseReady(context: Context): Boolean =
        FirebaseApp.getApps(context).isNotEmpty() || FirebaseApp.initializeApp(context) != null

    /**
     * OAuth web client id for Google sign-in. Prefers the value generated by the google-services
     * plugin (default_web_client_id) and falls back to GOOGLE_WEB_CLIENT_ID in local.properties.
     */
    @SuppressLint("DiscouragedApi")
    fun webClientId(context: Context): String {
        val id = context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
        val generated = if (id != 0) context.getString(id) else ""
        return generated.ifBlank { BuildConfig.GOOGLE_WEB_CLIENT_ID }
    }
}
